language: go
go:
  - 1.12.x

os:
  - linux

dist: trusty
sudo: false

install: true

env:
  - GO111MODULE=on

script:
  - go test ./...

notifications:
  email: false

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

